image: debian/buster
sources:
  - https://git.sr.ht/~mrlee/kamelasa
packages:
  - haskell-stack
  - ruby
  - ruby-dev
  - libffi-dev
  - zlib1g-dev
secrets:
  - f74304b4-9735-47a4-9d23-6d9fd7c47f1a
tasks:
  - publish: |
      cd kamelasa
      sudo gem install fpm
      sudo stack upgrade
      stack setup
      stack build
      fpm -s dir -t deb -n kamelasa -v $(cat VERSION) $(stack path --local-install-root)/kamelasa
      scp kamelasa_$(cat VERSION)_x86_64.deb deploy@kamelasa.mrlee.dev:/var/www/pkg.kamelasa.dev/
